/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevLoginRouteImport } from './routes/dev-login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as ApiStreamRouteImport } from './routes/api.stream'
import { Route as PSlugListRouteImport } from './routes/p.$slug.list'
import { Route as PSlugGoalsRouteImport } from './routes/p.$slug.goals'
import { Route as PSlugBoardRouteImport } from './routes/p.$slug.board'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLoginRoute = DevLoginRouteImport.update({
  id: '/dev-login',
  path: '/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugListRoute = PSlugListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugGoalsRoute = PSlugGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => PSlugRoute,
} as any)
const PSlugBoardRoute = PSlugBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => PSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev-login': typeof DevLoginRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/api/stream': typeof ApiStreamRoute
  '/join/$token': typeof JoinTokenRoute
  '/p/$slug': typeof PSlugRouteWithChildren
  '/p/$slug/board': typeof PSlugBoardRoute
  '/p/$slug/goals': typeof PSlugGoalsRoute
  '/p/$slug/list': typeof PSlugListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev-login': typeof DevLoginRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/api/stream': typeof ApiStreamRoute
  '/join/$token': typeof JoinTokenRoute
  '/p/$slug': typeof PSlugRouteWithChildren
  '/p/$slug/board': typeof PSlugBoardRoute
  '/p/$slug/goals': typeof PSlugGoalsRoute
  '/p/$slug/list': typeof PSlugListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev-login': typeof DevLoginRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/api/stream': typeof ApiStreamRoute
  '/join/$token': typeof JoinTokenRoute
  '/p/$slug': typeof PSlugRouteWithChildren
  '/p/$slug/board': typeof PSlugBoardRoute
  '/p/$slug/goals': typeof PSlugGoalsRoute
  '/p/$slug/list': typeof PSlugListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev-login'
    | '/login'
    | '/settings'
    | '/setup'
    | '/api/stream'
    | '/join/$token'
    | '/p/$slug'
    | '/p/$slug/board'
    | '/p/$slug/goals'
    | '/p/$slug/list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev-login'
    | '/login'
    | '/settings'
    | '/setup'
    | '/api/stream'
    | '/join/$token'
    | '/p/$slug'
    | '/p/$slug/board'
    | '/p/$slug/goals'
    | '/p/$slug/list'
  id:
    | '__root__'
    | '/'
    | '/dev-login'
    | '/login'
    | '/settings'
    | '/setup'
    | '/api/stream'
    | '/join/$token'
    | '/p/$slug'
    | '/p/$slug/board'
    | '/p/$slug/goals'
    | '/p/$slug/list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevLoginRoute: typeof DevLoginRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ApiStreamRoute: typeof ApiStreamRoute
  JoinTokenRoute: typeof JoinTokenRoute
  PSlugRoute: typeof PSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-login': {
      id: '/dev-login'
      path: '/dev-login'
      fullPath: '/dev-login'
      preLoaderRoute: typeof DevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug/list': {
      id: '/p/$slug/list'
      path: '/list'
      fullPath: '/p/$slug/list'
      preLoaderRoute: typeof PSlugListRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/goals': {
      id: '/p/$slug/goals'
      path: '/goals'
      fullPath: '/p/$slug/goals'
      preLoaderRoute: typeof PSlugGoalsRouteImport
      parentRoute: typeof PSlugRoute
    }
    '/p/$slug/board': {
      id: '/p/$slug/board'
      path: '/board'
      fullPath: '/p/$slug/board'
      preLoaderRoute: typeof PSlugBoardRouteImport
      parentRoute: typeof PSlugRoute
    }
  }
}

interface PSlugRouteChildren {
  PSlugBoardRoute: typeof PSlugBoardRoute
  PSlugGoalsRoute: typeof PSlugGoalsRoute
  PSlugListRoute: typeof PSlugListRoute
}

const PSlugRouteChildren: PSlugRouteChildren = {
  PSlugBoardRoute: PSlugBoardRoute,
  PSlugGoalsRoute: PSlugGoalsRoute,
  PSlugListRoute: PSlugListRoute,
}

const PSlugRouteWithChildren = PSlugRoute._addFileChildren(PSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevLoginRoute: DevLoginRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ApiStreamRoute: ApiStreamRoute,
  JoinTokenRoute: JoinTokenRoute,
  PSlugRoute: PSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
